name: deep-video-prior
channels:
  - soumith
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py27_0
  - astor=0.7.1=py27_0
  - backports=1.0=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports.weakref=1.0.post1=py27_0
  - backports_abc=0.5=py27_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2020.6.24=0
  - cairo=1.14.8=0
  - certifi=2019.11.28=py27_0
  - cuda80=1.0=0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py27_0
  - dbus=1.13.6=h746ee38_0
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - funcsigs=1.0.2=py27_0
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - gast=0.2.2=py27_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.14.1=py27h9ba97e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py27h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=54.1=0
  - intel-openmp=2019.3=199
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - jpeg=8d=2
  - jupyter_client=5.3.4=py27_0
  - jupyter_core=4.6.1=py27_0
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.1.0=py27he6710b0_0
  - lcms=1.19=0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.14=0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.4=0
  - linecache2=1.0.0=py27_0
  - markdown=3.1=py27_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py27h7dd41cf_0
  - mkl_random=1.0.1=py27h4414c95_1
  - mock=2.0.0=py27_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.15.0=py27h1793315_0
  - openssl=1.0.2u=h7b6447c_0
  - pathlib2=2.3.5=py27_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pil=1.1.7=py27_2
  - pip=19.1=py27_0
  - pixman=0.34.0=hceecf20_3
  - prompt_toolkit=1.0.15=py27_0
  - protobuf=3.6.1=py27he6710b0_0
  - ptyprocess=0.6.0=py27_0
  - pycairo=1.13.3=py27hea6d626_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.6.0=py27h22d08a2_6
  - python=2.7.15=h77bded6_2
  - python-dateutil=2.8.0=py27_0
  - pytz=2019.1=py_0
  - pyyaml=5.2=py27h7b6447c_0
  - qt=5.6.2=2
  - readline=7.0=h7b6447c_5
  - scandir=1.10.0=py27h7b6447c_0
  - scikit-learn=0.20.1=py27h4989274_0
  - scipy=1.1.0=py27hd20e5f9_0
  - setuptools=41.0.1=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.18=py27_0
  - six=1.12.0=py27_0
  - sqlite=3.28.0=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - tbb=2020.0=hfd86e86_0
  - tbb4py=2019.8=py27hfd86e86_0
  - tensorboard=1.13.1=py27hf484d3e_0
  - tensorflow=1.13.1=gpu_py27hcb41dfa_0
  - tensorflow-base=1.13.1=gpu_py27h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py27_1
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.3=py27_0
  - unittest2=1.1.0=py27_0
  - wcwidth=0.2.5=py_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.2=he6710b0_2
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - astroid==1.6.6
    - backports-functools-lru-cache==1.6.1
    - blessings==1.7
    - cloudpickle==0.8.1
    - configparser==4.0.2
    - dask==1.2.1
    - decorator==4.4.0
    - gpustat==0.6.0
    - idna==2.7
    - imageio==2.4.1
    - imgaug==0.4.0
    - isort==4.3.21
    - lazy-object-proxy==1.5.1
    - lxml==4.2.6
    - matplotlib==2.2.5
    - mccabe==0.6.1
    - msgpack==1.0.0
    - msgpack-numpy==0.4.4.3
    - networkx==2.2
    - numpy==1.15.4
    - nvidia-ml-py==375.53.1
    - opencv-python==4.1.0.25
    - pillow==6.0.0
    - progressbar2==3.38.0
    - psutil==5.6.3
    - pyexiftool==0.1.1
    - pylint==1.9.5
    - python-utils==2.4.0
    - pywavelets==1.0.3
    - pyzmq==18.1.1
    - requests==2.19.1
    - scikit-image==0.14.2
    - shapely==1.7.0
    - tabulate==0.8.6
    - tensorlayer==1.11.0
    - tensorpack==0.9.8
    - toolz==0.9.0
    - tqdm==4.27.0
    - ujson==1.35
    - urllib3==1.23
    - wrapt==1.10.11
    - youtube-dl==2020.1.24
prefix: /home/chenyang/anaconda3/envs/tensorflow

